name: Build

on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string
            python-version:
                required: true
                type: string

jobs:
    build:
        runs-on: ${{ inputs.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.11.14"
                  python-version: ${{ inputs.python-version }}

            - name: Installing the project
              run: uv sync --all-extras --dev

            - name: Run tests
              run: uv run pytest --doctest-modules tests
