# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: "**" # push to any branch
    pull_request:
        branches: "**" # push to any branch

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        runs-on: ubuntu-latest

        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools>=70.0.0
                  pip install flake8 pytest
                  pip install -r requirements_dev.txt
                  pip install -r requirements.txt

            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-${{ matrix.python-version }}
                  path: ./wheelhouse/*.whl
