name: Coverage
on:
    push:
        branches: "**" # push to any branch
    pull_request:
        branches: "**" # push to any branch

permissions:
    contents: read

jobs:
    build_wheels:
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]

        runs-on: ubuntu-latest

        name: Coverage Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools>=70.0.0
                  pip install pytest coverage coveralls
                  pip install -r requirements.txt

            - name: Build and install
              run: pip install .

            - name: Run coverage and send to coveralls
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  coverage run --source=digneapy -m pytest tests/
                  coveralls --service=github
