name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # or main if you are using the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy documentation
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.10"
          python-version: "3.13"
      
      - name: Install dependencies
        run: |
              uv add -r requirements_dev.txt
      
      - name: Build the site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          token: ${{ secrets.GITHUB_TOKEN }}