name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy documentation
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          # Install a specific version of uv.
          version: "0.11.14"
          python-version: "3.13"

      - name: Installing the project
        run: uv sync --all-extras --group dev

      - name: Build the site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
