# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: "**" # push to any branch
    pull_request:
        branches: "**" # push to any branch

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  check-latest: false
                  update-environment: true
                  allow-prereleases: false

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip setuptools
                  pip install flake8 pytest
                  pip install -r requirements.txt

            - name: Lint with flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Build and install
              run: python3 setup.py install

            - name: Test with pytest
              run: |
                  pytest --doctest-modules
