# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
    push:
        branches: "**" # push to any branch
    pull_request:
        branches: "**" # push to any branch

permissions:
    contents: read

jobs:
    build_wheels:
        name: Build wheels on Linux Systems
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.18.1

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-ubuntu-latest
                  path: ./wheelhouse/*.whl
